### ISSUE TITLE
No throw when graph has no edge

### ISSUE THREAD

**Issue by jacomyal** [graphology/graphology-communities-louvain#6]
Currently, this implementation throws an error if the input graph has no edge ([source](https://github.com/graphology/graphology-communities-louvain/blob/bc9e5c6a19a0e104454ad16881e03bc8033660bd/index.js#L55-L56)). It doesn't make sense to me, since it could instead simply set its own community to each node. This would allow developers to not have to check before calling this function.

**Comment by Yomguithereal** [comment]
This could be done but the issues lies with modularity. The modularity formulation has a division by 0 when there exist no edges. I need to make it return something like 0 or a min or a max but I am not sure to know what's the correct thing to do.

**Comment by jacomyal** [comment]
Why don't you just check the presence of edges *before* going through the normal process, and if no edge then return the trivial split, ie one community per node?

Then, I have a satisfying result, and you don't have to consider modularity computing with no edge.

**Comment by jacomyal** [comment]
(also, it definitely does seem more like a bug to me, since I don't have to know anything about modularity to use `graphology-communities-louvain`, so I shouldn't have to know the edge cases)
